services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    routing_manager:
        class: \PoP\RoutingWP\RoutingManager
        public: true

    PoP\RoutingWP\Hooks\:
        resource: '../src/Hooks/*'
        public: true
